[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "shop-api"
version = "0.1"
description = "Shop API."
dependencies = []

[tool.setuptools]
provides = ["shop"]